<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>MoeFleaRefresh</RootNamespace>
    <AssemblyName>MoeFleaRefresh</AssemblyName>
    <ImplicitUsings>enable</ImplicitUsings>
    <OutputType>Library</OutputType>
    <Version>1.1.1</Version>
    <OutputPath>..\..\dist\SPT_Runtime\user\mods\Moe-FleaRefresh\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SPTushonka.Common" Version="4.1.5" />
    <PackageReference Include="SPTushonka.DI" Version="4.1.5" />
    <PackageReference Include="SPTushonka.Reflection" Version="4.1.5" />
    <PackageReference Include="SPTushonka.Server.Core" Version="4.1.5" />
  </ItemGroup>

  <ItemGroup>
    <None Update="config.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <TargetPath>config.json</TargetPath>
    </None>
  </ItemGroup>
</Project>
